### ISSUE TITLE
WP Fluent Forms Customisation of button colours is reverting to default 

### ISSUE THREAD

**Issue by LissieNZ** [fluentform/fluentform#75]
Submit button> custom style. Changed the background and on hover background and text colours - they displayed on the form correctly, until I save the form, then  reverted to default light grey. 
![2021-03-12 15_13_05-Editor - Fluentform](https://user-images.githubusercontent.com/80497971/110881625-89a1da80-8345-11eb-941a-21b5582d01b6.png)
![2021-03-12 15_14_38-Editor - Fluentform](https://user-images.githubusercontent.com/80497971/110881729-b524c500-8345-11eb-9f3a-8243c939221d.png)

WP 5.7 
FF 3.6.70
Theme Beaver Builder

**Comment by nkb-bd** [comment]
Could not reproduce the issue, please check again with the latest version.
Thanks

**Comment by keeslina** [comment]
Hi, 

I'm experiencing the same problem.
FluentForms Pro 5.0.9
Wordpress 6.3.1

**Comment by nkb-bd** [comment]
Could not recreate the issue, if you are using any cache plugin try deactivating it, for support help you can open a support ticket in our [support portal](https://wpmanageninja.com/support-tickets/).

**Comment by jeanorific** [comment]
Hi guys, I came across the same issue and did find a solution that worked for me.
Theme: Hello Elementor

Solution:

1. Instead of adding the fluent forms widget into the page, add the shortcode widget.
2. Copy the shortcode of the form you built on fluent forms e.g [fluentform id="1"]
3. Paste this shortcode into the "Enter your shortcode" section in the shortcode widget settings.

lmk if this works for you too.
cheers!
